// GENERAL
const USER = "USER";
const SUCCESS = "SUCCESS";

// AXIOS
const POST = "POST";
const GET = "GET";

// AXIOS LOG TITLE
const POST_SEND_EMAIL = "POST_SEND_EMAIL";
const GET_GOOGLE_OAUTH2_TOKEN = "GET_GOOGLE_OAUTH2_TOKEN";
const GET_GOOGLE_OAUTH2_SCOPE = "GET_GOOGLE_OAUTH2_SCOPE";

// HEADER NAME
const X_SID = "x-sid";

// APP STATE
const DEV = "DEV";
const PREPROD = "PREPROD";
const PROD = "PROD";

// EMAIL TYPE
const SEND_OTP = "SEND_OTP";
const SEND_EMAIL_EXISTENCE = "SEND_EMAIL_EXISTENCE";
const SEND_NEW_PASSWORD_REQUEST =
  "SEND_NEW_PASSWORD_REQUEST";

// EMAIL SUBJECT
const ACCOUNT_SUCCESSFULLY_REGISTERED =
  "Account Registration - Your account has been sucessfully registered";
const OTP_EMAIL =
  "Account OTP Validation - Here is your OTP number";
const NEW_PASSWORD_REQUEST_EMAIL =
  "New Password Request - Please click this link to verify its you";

// API URLs
const SEND_MAIL = `v1/send`;

module.exports = {
  DEV,
  PREPROD,
  PROD,
  USER,
  SUCCESS,
  POST,
  GET,
  X_SID,
  POST_SEND_EMAIL,
  GET_GOOGLE_OAUTH2_TOKEN,
  GET_GOOGLE_OAUTH2_SCOPE,
  SEND_OTP,
  SEND_NEW_PASSWORD_REQUEST,
  SEND_EMAIL_EXISTENCE,
  SEND_MAIL,
  ACCOUNT_SUCCESSFULLY_REGISTERED,
  OTP_EMAIL,
  NEW_PASSWORD_REQUEST_EMAIL,
};
