
// GENERAL
const USER = "USER";
const SUCCESS = "SUCCESS";

// AXIOS
const POST = "POST";
const GET = "GET";

// AXIOS LOG TITLE
const POST_SEND_EMAIL = "POST_SEND_EMAIL";
const GET_GOOGLE_OAUTH2_TOKEN = "GET_GOOGLE_OAUTH2_TOKEN";
const GET_GOOGLE_OAUTH2_SCOPE = "GET_GOOGLE_OAUTH2_SCOPE";

// EMAIL TYPE
const SEND_OTP = "SEND_OTP";

// EMAIL SUBJECT
const OTP_EMAIL = "Account Registration - Here is your OTP number";

// API URLs
const SEND_MAIL = `v${process.env.APP_MAILER_MAJOR_VERSION}/send`;

module.exports = {
    USER,
    SUCCESS,
    POST,
    GET,
    POST_SEND_EMAIL,
    GET_GOOGLE_OAUTH2_TOKEN,
    GET_GOOGLE_OAUTH2_SCOPE,
    SEND_OTP,
    SEND_MAIL,
    OTP_EMAIL
}